### ISSUE TITLE
UnityAndroidPermissions not found on Flutter v1.12.13+hotfix.6 

### ISSUE THREAD

**Issue by assemmarwan** [snowballdigital/flutter-unity-view-widget#86]
After upgrading to flutter `v1.12.13+hotfix.6` (stable channel) Unity AR widget starts without a camera and doesn't ask for camera permission. However, running the app in debug mode works fine.

I have tried building using _appbundle_ & _apk_, but same result. This is the exception I get

![image](https://user-images.githubusercontent.com/5578999/71307432-bc417980-2407-11ea-9deb-1dd5109aa865.png)

It is working fine in debug & release mode in the previous stable version `v1.9.1+hotfix.6`.

I should mention that I had to add the below in UnityExport/build.gradle to make it build apk/appbundle.

```
    buildTypes {
        release {

        }
        profile {
        }
    }
```

Without the above, I get the following when executing `flutter build apk -v`:

```
[        ] > Task :UnityExport:prepareLintJarForPublish UP-TO-DATE
[ +475 ms] > Task :app:lintVitalRelease FAILED
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:lintVitalRelease'.
[        ] > Could not resolve all artifacts for configuration ':flutter_unity_widget:profileRuntimeClasspath'.
[        ]    > Could not resolve project :UnityExport.
[        ]      Required by:
[        ]          project :flutter_unity_widget
[        ]       > Unable to find a matching variant of project :UnityExport:
[        ]           - Variant 'debugApiElements' capability android:UnityExport:unspecified:
[        ]               - Incompatible attributes:
[        ]                   - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
[        ]                   - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
[        ]               - Other attributes:
[        ]                   - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
[        ]                   - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
[        ]           - Variant 'debugRuntimeElements' capability android:UnityExport:unspecified:
[        ]               - Incompatible attribute:
[        ]                   - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
[        ]               - Other attributes:
[        ]                   - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
[        ]                   - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
[        ]                   - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
[        ]           - Variant 'releaseApiElements' capability android:UnityExport:unspecified:
[        ]               - Incompatible attributes:
[        ]                   - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'release'.
[        ]                   - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
[        ]               - Other attributes:
[        ]                   - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
[        ]                   - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
[        ]           - Variant 'releaseRuntimeElements' capability android:UnityExport:unspecified:
[        ]               - Incompatible attribute:
[        ]                   - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'release'.
[        ]               - Other attributes:
[        ]                   - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
[        ]                   - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
[        ]                   - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 7s
[        ] 387 actionable tasks: 333 executed, 54 up-to-date
[ +378 ms] Running Gradle task 'assembleRelease'... (completed in 69.4s)
[   +6 ms] "flutter apk" took 70,344ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
<asynchronous suspension>
#2      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#3      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:106:26)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#7      _rootRun (dart:async/zone.dart:1126:13)
#8      _CustomZone.run (dart:async/zone.dart:1023:19)
#9      _runZoned (dart:async/zone.dart:1518:10)
#10     runZoned (dart:async/zone.dart:1465:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _runZoned (dart:async/zone.dart:1518:10)
#19     runZoned (dart:async/zone.dart:1465:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#27     _rootRun (dart:async/zone.dart:1126:13)
#28     _CustomZone.run (dart:async/zone.dart:1023:19)
#29     _runZoned (dart:async/zone.dart:1518:10)
#30     runZoned (dart:async/zone.dart:1502:12)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _runZoned (dart:async/zone.dart:1518:10)
#36     runZoned (dart:async/zone.dart:1465:12)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#38     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#39     run (package:flutter_tools/runner.dart:50:10)
#40     main (package:flutter_tools/executable.dart:65:9)
#41     main (file:///Users/anonymous/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by assemmarwan** [comment]
EUREKA!

Just added one line in `UnityExport/proguard-unity.txt`:

**`-keep class com.unity3d.plugin.* { *; }`**

Although, it's still unknown why it works on Flutter `v1.9.1+hotfix.6` without this line 🤷‍♂️
